### ISSUE TITLE
sanitize CHX profile_collection repo

### ISSUE THREAD

**Issue by cowanml** [NSLS2/chx-profile-collection#9]
https://github.com/search?q=org%3ANSLS-II-CHX+password&type=Code

username and password needs to be removed from all the repos/files listed in this search and git history of each repo sanitized :(

I strongly suggest auditing all other nsls2 orgs for any occurrence of "password", "passwd', "secret", etc
https://nsls-ii.github.io/gh-orgs-list.html#

I wouldn't wish this pain on anyone :(  Probably *very much* worth looking into
pre-commit and pre-receive hooks to check for and block blatant stuff like this as early as possible!

I'll contact chx to coordinate changing the password.
-matt

**Comment by mrakitin** [comment]
I strongly agree with Matt that storing the passwords as plain text, and especially in a public version control system is a poor choice. DAMA will make it a task to check if passwords are used in each beamline's profile on the next deployment visit.

**Comment by mrakitin** [comment]
I added 2 tasks to [Basecamp](https://3.basecamp.com/3733838/buckets/13952700/todosets/2108342451) for the next deployment "Deploy 20-1":

![image](https://user-images.githubusercontent.com/13209176/66242255-3bf45d80-e6cf-11e9-9d12-493188f97d88.png)

![image](https://user-images.githubusercontent.com/13209176/66242275-4e6e9700-e6cf-11e9-8461-5bc1495b461b.png)

**Comment by cowanml** [comment]
Is there anything else anyone can think of that involves usernames and passwords
or shared secrets or something that is handled in python and could have snuck into
a repo?  Mongo credentials?  credentials for any service-ified DAMA libraries? 
PASS api tokens? ???

Should probably move this discussion out of a public forum and into
basecamp or something?

-matt

**Comment by mrakitin** [comment]
This particular concern is resolved now, and the compromised file was sanitized, and eventually removed from the repo (see https://github.com/NSLS-II-CHX/profile_collection/pull/11).
